import {  dashboard, logoutIcon, profile } from '../assets';

export const navlinks = [
  {
    name: 'dashboard',
    imgUrl: dashboard,
    link: '/',
  },
 
  {
    name: 'profile',
    imgUrl: profile,
    link: '/profile',
  },
  {
    name: 'logout',
    imgUrl: logoutIcon,
    link: '/',
    disabled: true,
    
  },
];


export const currencies   = [
  "Bitcoin",
  "Ethereum",
  "Litecoin",
  "Ripple",
  "Cardano",
  "Polkadot",
  "Dogecoin",
  "Chainlink",
  "Stellar",
  "Solana",
  "Uniswap",
  "VeChain",
  "Tron",
  "Neo",
  "Cosmos",
  "Monero",
  "Tezos",
  "Zcash",
  "Dash",
  "IOTA",
  "EOS",
  "BAT (Basic Attention Token)",
  "Filecoin",
  "Aave",
  "Compound",
  "Synthetix",
  "Maker",
  "Yearn.finance",
  "SushiSwap",
  "Curve DAO",
  "Decentraland",
  "The Graph",
  "Theta Network",
];
export const preferredBlockchainTechnologies = [
  "Proof-of-Work",
  "Proof-of-Stake",
  "Delegated Proof-of-Stake (DPoS)",
  "Proof-of-Burn",
  "Proof-of-Capacity",
  "Proof-of-Elapsed-Time (PoET)",
  "Practical Byzantine Fault Tolerance (PBFT)",
  "HoneyBadgerBFT",
  "Tendermint",
  "Ripple Protocol Consensus Algorithm (RPCA)",
  "Directed Acyclic Graph (DAG)",
  "Hashgraph",
  "Algorand Consensus Algorithm",
  "Ouroboros",
  "Chia",
  "Casper (Friendly Finality Gadget)",
  "Ouroboros Praos",
  "Ouroboros Genesis",
  "Ouroboros Hydra",
  "Avalanche Consensus",
  "Scrypt",
  "Ethash",
  "Equihash",
  "RandomX",
  "Argon2",
  "Cryptonight",
  "Balloon Hashing",
  "Momentum",
  "Cuckoo Cycle",
  "Blake2",
  "X11",
  "X16R",
  "X16S",
  "X17",
  "Keccak",
  "CryptoNightV7",
  "CryptoNightR",
  "CryptoNight-Heavy",
  "CryptoNightV8",
  "RandomKEVA",
  "ProgPOW",
  "SHA-256",
  "Ethash",
  "X25X",
  "Zhash",
];

export const investmentSize = ["Small (up to $1,000)", "Medium ($1,000 - $10,000)", "Large ($10,000 and above)"];
export const investmentDuration = ["Short-term (less than 6 months)", "Medium-term (6 months to 1 year)", "Long-term (more than 1 year"];
export const riskTolerance = ["Low", "Medium", "High"];

export const carbonFootprintConcerns = ["Low", "Medium", "High"];
